var items = document.getElementsByClassName('list-group-item');
console.log(items);
console.log(items[1]);
items[1].textcontent= 'Hello2';
items[0].style.fontWeight='Bold';
items[1].style.fontWeight='Bold';
items[2].style.fontWeight='Bold';
items[3].style.fontWeight='Bold';
items[1].style.backgroundColor = 'Yellow';
items[2].style.backgroundColor = 'green';